name: linter-check
on: [push]
jobs:
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        with:
        node-version: '14.x'
        run: make install
      - name: Run linter
        run: make lint
